// ═══════════════════════════════════════
// DADOS — Figuras do Aranha-Verso e Simbiontes
// ═══════════════════════════════════════

const FIGURES = [
  {
    slug: "spiderman-616",
    name: "Homem-Aranha",
    alias: "Peter Parker",
    earth: "Terra-616",
    issue: "#001",
    img: "img/figures/spiderman-616.webp",
    cutout: "img/cutouts/spiderman.png",
    tag: "O Original",
    powers: ["Força e agilidade aracnídeas", "Sentido-aranha", "Teias orgânicas/mecânicas", "Fator de cura acelerado"],
    text: "Picado por uma aranha radioativa numa feira de ciências em Queens, Peter Parker é o Homem-Aranha que deu origem a todo o multiverso aracnídeo. \"Com grandes poderes vêm grandes responsabilidades\" nasceu com ele — e é a frase que qualquer Aranha de qualquer Terra acaba repetindo, do jeito dele.",
  },
  {
    slug: "miles-morales",
    name: "Homem-Aranha",
    alias: "Miles Morales",
    earth: "Terra-1610",
    issue: "#1610",
    img: "img/figures/miles-morales.webp",
    cutout: "img/cutouts/miles-morales.png",
    tag: "O Herdeiro",
    powers: ["Camuflagem (invisibilidade)", "Choque venenoso (Venom Blast)", "Força e agilidade aracnídeas", "Sentido-aranha próprio"],
    text: "Picado por uma aranha geneticamente modificada roubada da Oscorp, Miles herdou o manto após a morte do Peter Parker de seu universo. Ganhou poderes que nenhum outro Homem-Aranha tem — e uma frase de efeito que ecoou por todo o Aranha-Verso: qualquer um pode vestir a máscara.",
  },
  {
    slug: "spider-gwen",
    name: "Aranha-Gwen",
    alias: "Gwen Stacy",
    earth: "Terra-65",
    issue: "#065",
    img: "img/figures/spider-gwen.webp",
    cutout: "img/cutouts/spider-gwen.png",
    tag: "A Baterista",
    powers: ["Força e agilidade aracnídeas", "Sentido-aranha", "Teias próprias", "Baterista da banda Mary Janes"],
    text: "Em uma Terra onde foi ela — e não Peter — quem levou a picada da aranha radioativa, Gwen Stacy equilibra a vida de heroína com os shows da sua banda. Sua relação com o pai, capitão da polícia, e com um Peter Parker que segue caminhos bem diferentes do usual dá um tom só dela à história.",
  },
  {
    slug: "spiderman-2099",
    name: "Homem-Aranha 2099",
    alias: "Miguel O'Hara",
    earth: "Terra-928",
    issue: "#2099",
    img: "img/figures/spiderman-2099.webp",
    cutout: "img/cutouts/spiderman-2099.png",
    tag: "O Do Futuro",
    powers: ["Garras e presas retráteis", "Veneno paralisante na mordida", "Visão em modo aranha", "Teias de seda orgânica"],
    text: "Num futuro distópico controlado por megacorporações, o geneticista Miguel O'Hara testou em si mesmo um retrovírus que devia reescrever seu DNA com genes de aranha — só que um sabotador trocou a amostra por DNA humano, fundindo os dois de vez. Hoje ele também lidera a guarda que protege a estabilidade do multiverso.",
  },
  {
    slug: "iron-spider",
    name: "Homem-Aranha de Ferro",
    alias: "Peter Parker",
    earth: "Terra-616",
    issue: "#529",
    img: "img/figures/iron-spider.webp",
    cutout: "img/cutouts/iron-spider.png",
    tag: "O Blindado",
    powers: ["Quatro braços mecânicos retráteis", "Força e resistência amplificadas", "Planeio e visão tática integrada", "Teias reforçadas em nanotecnologia"],
    text: "Construído por Tony Stark durante a Guerra Civil dos heróis, o traje Aranha de Ferro trocou o lycra pela tecnologia Stark: braços mecânicos extras, resistência a impacto e um arsenal digno de um Vingador. Peter usou, se arrependeu, devolveu — mas o visual entrou pra história.",
  },
  {
    slug: "spider-ham",
    name: "Aranha-Porco",
    alias: "Peter Porker",
    earth: "Terra-8311",
    issue: "#8311",
    img: "img/figures/spider-ham.webp",
    cutout: "img/cutouts/spider-ham.png",
    tag: "O Toon",
    powers: ["Física dos desenhos animados (Toon Force)", "Força e reflexos aracnídeos", "Sobrevive a qualquer captura e piada visual"],
    text: "Numa Terra onde toda a vida inteligente evoluiu de animais de fazenda em vez de primatas, Peter Porker foi picado por uma aranha radioativa igual a tantas outras — só que aqui as leis da física são as dos desenhos animados. A prova viva de que o Aranha-Verso também sabe rir de si mesmo.",
  },
  {
    slug: "spider-punk",
    name: "Aranha-Punk",
    alias: "Hobart Brown",
    earth: "Terra-138",
    issue: "#138",
    img: "img/figures/spider-punk.webp",
    cutout: "img/cutouts/spider-punk.png",
    tag: "O Anarquista",
    powers: ["Toque vibracional (destrói tecnologia e concreto)", "Força e agilidade aracnídeas", "Guitarrista e vocalista de banda punk", "Sentido-aranha próprio"],
    text: "Numa Terra dominada por um governo autoritário, Hobie Brown usa a picada de aranha e uma guitarra quebrada pra liderar a resistência contra o sistema. Seu visual — colagem de recortes de jornal e zine — muda de forma quadro a quadro, porque nem a estética dele aceita ficar parada.",
  },
  {
    slug: "spider-woman",
    name: "Mulher-Aranha",
    alias: "Jessica Drew",
    earth: "Terra-616",
    issue: "#001",
    img: "img/figures/spider-woman.webp",
    cutout: "img/cutouts/spider-woman.png",
    tag: "A Pioneira",
    powers: ["Choques bioelétricos (Venom Blast)", "Planeio com membranas entre braço e tronco", "Feromônios que atraem ou repelem", "Força e agilidade aracnídeas"],
    text: "Exposta ainda bebê a um soro experimental à base de veneno de aranha, Jessica Drew foi a primeira mulher a usar o nome Mulher-Aranha nos quadrinhos, décadas antes de qualquer outra versão aparecer. Hoje soma detetive particular, ex-agente da S.H.I.E.L.D. e uma das aranhas mais experientes de qualquer Terra.",
  },
];

const SYMBIOTES = [
  {
    slug: "venom",
    name: "Venom",
    alias: "Eddie Brock",
    earth: "Terra-616",
    issue: "#300",
    img: "img/symbiotes/venom.webp",
    tag: "O Outro Lado",
    powers: ["Todos os poderes do hospedeiro simbionte", "Metamorfose e camuflagem", "Invisível ao sentido-aranha", "Presas e língua prênsil"],
    text: "Rejeitado por Peter Parker, o simbionte alienígena de Klyntar encontrou em Eddie Brock — jornalista arruinado pelo próprio Homem-Aranha — o hospedeiro perfeito para uma vingança em dobro. Com o tempo, a dupla trocou o ódio puro por uma parceria estranha, virando um dos anti-heróis mais queridos da Marvel.",
  },
  {
    slug: "carnage",
    name: "Carnage",
    alias: "Cletus Kasady",
    earth: "Terra-616",
    issue: "#361",
    img: "img/symbiotes/carnage.webp",
    tag: "A Prole",
    powers: ["Fusão molecular com o hospedeiro", "Formação de lâminas e armas orgânicas", "Regeneração extrema", "Imprevisibilidade total"],
    text: "Gerado a partir do simbionte Venom e ligado permanentemente ao sistema sanguíneo do serial killer Cletus Kasady, Carnage é puro caos sem filtro. Sem o código moral que Eddie Brock impõe ao seu simbionte, ele é considerado uma das ameaças mais destrutivas que o Homem-Aranha e o próprio Venom já enfrentaram juntos.",
  },
  {
    slug: "anti-venom",
    name: "Anti-Venom",
    alias: "Eddie Brock",
    earth: "Terra-616",
    issue: "#569",
    img: "img/symbiotes/anti-venom.webp",
    tag: "O Antídoto",
    powers: ["Cura outras pessoas ao toque", "Anula outros simbiontes e drogas do organismo", "Camuflagem branca e força aumentada"],
    text: "Quando os restos do simbionte original se fundiram com as células curativas do próprio sangue de Eddie Brock, nasceu uma versão purificada e branca do Venom — capaz de curar em vez de infectar. Um raro caso no Aranha-Verso em que o próprio simbionte vira remédio.",
  },
  {
    slug: "knull",
    name: "Knull",
    alias: "O Deus Simbionte",
    earth: "Terra-616",
    issue: "#001 (Eras Antigas)",
    img: "img/symbiotes/knull.webp",
    tag: "A Origem",
    powers: ["Criador de todos os simbiontes", "Controle absoluto sobre o Codex simbionte", "Imortalidade e força divina primordial", "Empunha a Necroespada"],
    text: "Muito antes de qualquer Aranha existir, Knull já reinava sozinho na escuridão entre as estrelas — até criar os simbiontes para conquistar a luz que os deuses trouxeram ao universo. Todo simbionte que já apareceu no Aranha-Verso, de Venom a Carnage, carrega um pedaço da vontade dele.",
  },
];

const MEDIA = [
  {
    title: "Across the Spider-Verse",
    subtitle: "Longa-metragem · 2023",
    img: "img/games/across-spiderverse.webp",
    pos: "center 18%",
    text: "A sequência que expandiu o multiverso aracnídeo pras telas com uma identidade visual própria pra cada dimensão.",
  },
  {
    title: "Into the Spider-Verse",
    subtitle: "Longa-metragem · 2018",
    img: "img/games/into-spiderverse.webp",
    pos: "center 15%",
    text: "O filme que apresentou Miles Morales ao grande público e reinventou o que uma animação de herói pode parecer.",
  },
  {
    title: "Marvel's Spider-Man 2",
    subtitle: "Jogo · PS5, 2023",
    img: "img/games/spiderman2-game.webp",
    pos: "center 22%",
    text: "Peter e Miles dividem o mesmo jogo pela primeira vez, com o simbionte preto no centro da história.",
  },
];
